version: '3.8'

# Common configurations
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-healthcheck-config: &default-healthcheck
  test: ["CMD-SHELL", "echo 'default'"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 10s

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: cildb
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: cil_cbt_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    networks:
      - cil-network
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cildb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging: *default-logging
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      DATABASE_URL: postgresql://cildb:${DB_PASSWORD}@postgres:5432/cil_cbt_db
      SECRET_KEY_FILE: /run/secrets/secret_key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      GOOGLE_CLIENT_ID_FILE: /run/secrets/google_client_id
      GOOGLE_CLIENT_SECRET_FILE: /run/secrets/google_client_secret
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - type: volume
        source: backend_cache
        target: /app/.cache
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cil-network
    secrets:
      - secret_key
      - google_client_id
      - google_client_secret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging: *default-logging
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      target: development
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    networks:
      - cil-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging: *default-logging
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

volumes:
  pgdata:
    name: cil_pgdata
    driver: local
  backend_cache:
    name: cil_backend_cache
    driver: local
  node_modules:
    name: cil_node_modules
    driver: local

networks:
  cil-network:
    name: cil_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

secrets:
  db_password:
    file: ./secrets/db_password.txt
  secret_key:
    file: ./secrets/secret_key.txt
  google_client_id:
    file: ./secrets/google_client_id.txt
  google_client_secret:
    file: ./secrets/google_client_secret.txt