# docker-compose.dev.yml
version: '3.8'

# Common configurations
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-healthcheck-config: &default-healthcheck
  test: ["CMD-SHELL", "echo 'default'"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 10s

services:
  postgres:
    image: postgres:15-alpine
    container_name: cil_hr_postgres
    environment:
      # Hardcoding these essential variables directly for robustness
      POSTGRES_USER: cildb
      POSTGRES_PASSWORD: cildb123
      POSTGRES_DB: cil_cbt_db
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=en_US.utf8 --lc-ctype=en_US.utf8"
    # Removed env_file from postgres service, as variables are now hardcoded
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
      - ./backend/init:/docker-entrypoint-initdb.d
    networks:
      - cil-network
    healthcheck:
      # Update healthcheck to use hardcoded values
      test: ["CMD-SHELL", "pg_isready -U cildb -d cil_cbt_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging: *default-logging
    # Memory optimization for WSL constraints
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    command: >
      sh -c "
        echo 'PostgreSQL Environment Variables:' &&
        env | grep POSTGRES_PASSWORD &&
        env | grep POSTGRES_USER &&
        env | grep POSTGRES_DB &&
        /usr/local/bin/docker-entrypoint.sh postgres
          -c shared_buffers=128MB
          -c effective_cache_size=256MB
          -c maintenance_work_mem=32MB
          -c checkpoint_completion_target=0.9
          -c wal_buffers=8MB
          -c default_statistics_target=100
          -c random_page_cost=1.1
          -c effective_io_concurrency=200
          -c work_mem=2MB
          -c min_wal_size=1GB
          -c max_wal_size=4GB
      "

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    env_file:
      - ./.env.dev
    environment:
      SECRET_KEY_FILE: /run/secrets/secret_key
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      GOOGLE_CLIENT_ID_FILE: /run/secrets/google_client_id
      GOOGLE_CLIENT_SECRET_FILE: /run/secrets/google_client_secret
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - type: volume
        source: backend_cache
        target: /app/.cache
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cil-network
    secrets:
      - secret_key
      - google_client_id
      - google_client_secret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging: *default-logging
    # Optimized memory settings for WSL constraints
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 400M
    command: sh -c "echo 'Backend Environment Variables:' && env | grep POSTGRES_PASSWORD && env | grep DATABASE_URL && python -c 'import gc; gc.enable(); gc.set_threshold(100, 5, 5)' && python /app/init_db.py && PYTHONUNBUFFERED=1 PYTHONGC=1 uvicorn src.main:app --host 0.0.0.0 --port 8000 --limit-concurrency 8 --timeout-keep-alive 5 --workers 1"

  frontend:
    build:
      context: ./frontend
      target: development
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID}
      - WATCHPACK_POLLING=${WATCHPACK_POLLING}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
      # Memory optimization settings
      - GENERATE_SOURCEMAP=false
      - NODE_OPTIONS=--max_old_space_size=1024
      - REACT_APP_STRICT_MODE=false
      - WDS_SOCKET_PORT=0
    networks:
      - cil-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    # Add memory limit for 8GB RAM system
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    logging: *default-logging

volumes:
  pgdata:
    name: cil_pgdata
    driver: local
  backend_cache:
    name: cil_backend_cache
    driver: local
  node_modules:
    name: cil_node_modules
    driver: local

networks:
  cil-network:
    name: cil_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

secrets:
  secret_key:
    file: ./secrets/secret_key.txt
  google_client_id:
    file: ./secrets/google_client_id.txt
  google_client_secret:
    file: ./secrets/google_client_secret.txt