version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    env_file: .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cil-network

  backend:
    build: ./backend
    env_file: .env.prod
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - cil-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - cil-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:

networks:
  cil-network:
    driver: bridge