version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cil_hr_postgres
    environment:
      POSTGRES_USER: cildb
      POSTGRES_PASSWORD: cildb123
      POSTGRES_DB: cil_cbt_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d cil_hr_exam_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: