"""Add questions difficulty calculation

Revision ID: 0980bb7d7827
Revises: 3f82c5a198e4
Create Date: 2025-06-20 01:38:01.711411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0980bb7d7827'
down_revision: Union[str, None] = '3f82c5a198e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('numeric_difficulty', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'numeric_difficulty')
    # ### end Alembic commands ###
